# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: op.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'op.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08op.proto\"B\n\x0eRegUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x11\n\trequestId\x18\x03 \x01(\t\"\"\n\x0fRegUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"E\n\x11UpdateUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x11\n\trequestId\x18\x03 \x01(\t\"%\n\x12UpdateUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"5\n\x11\x44\x65leteUserRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x11\n\trequestId\x18\x02 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"&\n\x15GetLatestValueRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"Y\n\x16GetLatestValueResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\"7\n\x17\x43\x61lcAvarageValueRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"O\n\x18\x43\x61lcAvarageValueResponse\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x14\n\x0c\x61verageValue\x18\x03 \x01(\x01\x32\xbb\x02\n\x0cUser_service\x12\x31\n\x0cRegisterUser\x12\x0f.RegUserRequest\x1a\x10.RegUserResponse\x12\x35\n\nUpdateUser\x12\x12.UpdateUserRequest\x1a\x13.UpdateUserResponse\x12\x35\n\nDeleteUser\x12\x12.DeleteUserRequest\x1a\x13.DeleteUserResponse\x12\x41\n\x0eGetLatestValue\x12\x16.GetLatestValueRequest\x1a\x17.GetLatestValueResponse\x12G\n\x10\x43\x61lcAvarageValue\x12\x18.CalcAvarageValueRequest\x1a\x19.CalcAvarageValueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'op_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGUSERREQUEST']._serialized_start=12
  _globals['_REGUSERREQUEST']._serialized_end=78
  _globals['_REGUSERRESPONSE']._serialized_start=80
  _globals['_REGUSERRESPONSE']._serialized_end=114
  _globals['_UPDATEUSERREQUEST']._serialized_start=116
  _globals['_UPDATEUSERREQUEST']._serialized_end=185
  _globals['_UPDATEUSERRESPONSE']._serialized_start=187
  _globals['_UPDATEUSERRESPONSE']._serialized_end=224
  _globals['_DELETEUSERREQUEST']._serialized_start=226
  _globals['_DELETEUSERREQUEST']._serialized_end=279
  _globals['_DELETEUSERRESPONSE']._serialized_start=281
  _globals['_DELETEUSERRESPONSE']._serialized_end=318
  _globals['_GETLATESTVALUEREQUEST']._serialized_start=320
  _globals['_GETLATESTVALUEREQUEST']._serialized_end=358
  _globals['_GETLATESTVALUERESPONSE']._serialized_start=360
  _globals['_GETLATESTVALUERESPONSE']._serialized_end=449
  _globals['_CALCAVARAGEVALUEREQUEST']._serialized_start=451
  _globals['_CALCAVARAGEVALUEREQUEST']._serialized_end=506
  _globals['_CALCAVARAGEVALUERESPONSE']._serialized_start=508
  _globals['_CALCAVARAGEVALUERESPONSE']._serialized_end=587
  _globals['_USER_SERVICE']._serialized_start=590
  _globals['_USER_SERVICE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
